# development:
# <<: *default
# database: fido_development
# username: user
# password: abcdef
# adapter: postgresql
# host: localhost
# encoding: unicode


# test:
# <<: *default
# database: SM_test
# username: user
# password: abcdef
# adapter: postgresql
# encoding: unicode

# production:
# <<: *default
# database: SM_production
# username: user
# password: abcdef

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: abcdef
  # I use "abcdef" as a postgresql password for development on open projects. It's easy to type really fast and doesn't actually reveal any real passwords or password naming schemes
  

development:
  <<: *default
  database: fetch-a-fido